#This file contains information about the node group where the AI agent is running.
# nodegroup-ai-agent.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ai-agent-k8s-cluster
  region: eu-central-1

managedNodeGroups:
  - name: ai-agent-pool
    instanceTypes:
      - m6i.xlarge
      - m5.xlarge
      - m6a.xlarge
    spot: true
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 50
    labels:
      workload: ai-agent
    taints:
      - key: workload
        value: ai-agent
        effect: NoSchedule
    tags:
      purpose: k8s-ai-ops-agent
